# General
title:          Emanuele Frasca
description:    Computer and Artificial Intelligence Engineer
url:            https://noostale.github.io
baseurl:        ""

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed
  sourcemap: never

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  
highlighter: rouge

livereload: true

exclude:
  - new_post.sh
